# Generated by Django 4.0.1 on 2022-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=50)),
                ('email', models.EmailField(default='empty', max_length=100)),
                ('phone', models.CharField(default='empty', max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
