# Generated by Django 4.0.1 on 2022-11-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bertModel', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
    ]
